### PR TITLE
update elab for WithFC

### PR DESCRIPTION
**Pull request by andrevidela**
fix for https://github.com/idris-lang/Idris2/pull/3423

### CODE REVIEW

**Review by mattpolzin — COMMENTED** [review]
This looks good. Since CI isn't set up to test against an arbitrary upstream commit of the compiler I'll test this compiles for me locally on my laptop before approving.

**Comment by alexhumphreys** [comment]
Ah, looks like the tests are building against the docker image `snazzybucket/idris2`, which hasn't been updated in 11 months. So if you're testing against [an open idris2 PR](https://github.com/idris-lang/Idris2/pull/3423) that's gonna be trickier, can see now why @mattpolzin offered to test locally!

**Review by mattpolzin — APPROVED** [review]
Tested locally.
```
./build/exec/runtests idrall --interactive --only

------------------------------------------------------------------------
dhall-lang tests
------------------------------------------------------------------------

idrall/idrall001: success
idrall/idrall002: success
idrall/idrall003: success
idrall/idrall004: success
idrall/idrall005: success

------------------------------------------------------------------------
dhall-lang expected fail tests
------------------------------------------------------------------------

failure/failure001: success

------------------------------------------------------------------------
derive tests
------------------------------------------------------------------------

derive/derive001: success
derive/derive002: success
derive/derive003: success

------------------------------------------------------------------------
examples tests
------------------------------------------------------------------------

examples/example001: success
examples/example002: success
examples/example003: success
examples/inigo001: success
13/13 tests successful
```

**Comment by andrevidela** [comment]
Thank you so much!

**Comment by mattpolzin** [comment]
upstream has merged; I'll merge this. Sounds like Alex was discovering the Docker image this CI uses has not been updated recently so we will have broken CI going forward until that is fixed, but that's a problem for a separate PR.

**Comment by andrevidela** [comment]
Thanks

**Pull request merged**
