### PR TITLE
[ compat ] Idris2 now ships a Show for parse errors

### PR DESCRIPTION
**Pull request by gallais**

### CODE REVIEW

**Comment by alexhumphreys** [comment]
Looks like the tests fail because of diffs in the output for the failing cases. You can run the tests with `make tests` then commit the new output, or I can do it if you like?

**Comment by gallais** [comment]
I'll do it after the easter holidays. :+1:

**Comment by gallais** [comment]
Hmmm
```
1/1: Building Good (Good.idr)
Main> Result:
Pass: 0
Fail: 0
Main> Bye for now!
```
Ah, I see I need to `git submodule update` before running `make test`.

**Comment by alexhumphreys** [comment]
Ah nice one, thanks for this. Haven't used hints before, that syntax is pretty wild, but glad it works!
And there's a not in the README about needing the submodule to run the tests, but it's pretty easy to miss. I should probably add a `make` target that checks if the submodule is there before running the tests, so it could output a more helpful message if it's missing.

**Pull request merged**
